apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter
  template:
    metadata:
      labels:
        app: counter
    spec:
      containers:
      - name: counter
        image: counter:v0.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 20
            memory: "500Mi"
          limits:
            cpu: 20
            memory: "800Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: counter-service
spec:
  selector:
    app: counter
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080  # Changed from 8080 to 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: counter-ingress
spec:
  defaultBackend:
    service:
      name: counter-service
      port:
        number: 80
  rules:
  - http:
      paths:
      - path: /  # Adjust the path as needed
        pathType: Prefix
        backend:
          service:
            name: counter-service
            port:
              number: 80
